[tool.semantic_release]
assets = []
build_command_env = ['GH_TOKEN']
build_command = 'echo "Building" '
commit_message = "ci(semantic-release): automatic update - v{version}"
commit_parser = "angular"

logging_use_named_masks = false
allow_zero_version = true
major_on_zero = true
no_git_verify = false

tag_format = "v{version}"
upload_to_release = true
template_dir="./github/templates"

[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "FacsimiLab [BOT] <195262995+facsimilab-bot@users.noreply.github.com>"

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test"]
minor_tags = ["feat", "docs"]
patch_tags = ["fix", "perf"]
default_bump_level = 0

[tool.semantic_release.default_templates]
changelog_file = "CHANGELOG.md"
output_format="md"
template_dir="./github/templates"

[tool.semantic_release.branches.release]
match = "release"
prerelease = false

[tool.semantic_release.branches.rc]
match = "rc/*"
prerelease_token = "rc"
prerelease = true

[tool.semantic_release.branches.main]
match = "main"
# Pre-release is set to true, but the GitHub action will not create a tag or release on this branch
prerelease = true
prerelease_token = "main"

[tool.semantic_release.branches.adjusted]
match = "adjusted/*"
# Pre-release is set to true, but the GitHub action will not create a tag or release on this branch
prerelease = true
prerelease_token = "develop"


[tool.semantic_release.changelog]
changelog_file = "CHANGELOG.md"

[tool.semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = true

[tool.semantic_release.remote]
name = "origin"
type = "github"
ignore_token_for_push = true
insecure = false