name: Add issues and PRs to BFGI GitHub Project 

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue and PR to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: https://github.com/orgs/FacsimiLab-Rush/projects/6
          github-token: ${{ secrets.GH_PROJECT_PAT }}