on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
      - rc
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

name: Render and Publish

# you need these permissions to publish to GitHub pages
permissions: 
    contents: write
    pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    if: ${{github.repository_owner}} != 'FacsimiLab' && ${{github.repository}} != 'Facsimilab/protocol-template'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4


      - uses: actions/setup-python@v4
        name: Install python packages
        with:
          python-version: '3.11'
      - run: pip install jupyter jupyter-cache
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tinytex: true 
          # version: SPECIFIC-QUARTO-VERSION-HERE


      # Remember, you have to first run `quarto publish gh-pages` locally 1 time to initilize this branch
      - name: Publish to GitHub Pages (and render) 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
